name: CI

on:
  push:
    branches: [ "main" ]

jobs:

  ci:

    runs-on: ubuntu-latest

    steps:
    -
     name: Chekout
     uses: actions/checkout@v3
    
    - 
      name: DockerHub Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS }}
           
    - 
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/ntcproject:latest
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/ntcproject:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/ntcproject:buildcache,mode=max
        
    - 
      name: Webhook
      uses: distributhor/workflow-webhook@v2
      env:
        webhook_url: ${{ secrets.WEBHOOK_URL }}
        webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
